/**
 * ChunkManager - Fixed-size chunk-based world subdivision
 *
 * Divides the world into fixed-size chunks (e.g., 8m × 8m).
 * Each chunk is a fully independent mini-world:
 * - Processes ONLY its own region (no ghost cells)
 * - Generates its own loops via marching squares
 * - Manages its own physics colliders
 * - Tracks whether it's dirty
 *
 * Benefits:
 * - True independence (no ownership filtering needed)
 * - Predictable boundaries (no dynamic expansion)
 * - Atomic updates (delete all old colliders, create all new ones)
 * - Parallelizable (chunks don't depend on neighbors)
 * - Simple and robust (no edge cases)
 *
 * Trade-offs:
 * - Small visual/physics seams at chunk boundaries (acceptable)
 * - Slightly more total vertices (boundary edges duplicated)
 */

import type { AABB, Point } from './types';
import type { DensityField } from './DensityField';

/**
 * A single chunk in the world grid
 * Each chunk is a fully independent mini-world that processes only its own region
 */
export interface Chunk {
  // Grid coordinates (chunk indices, not world/cell coordinates)
  gridX: number;
  gridY: number;

  // Chunk bounds in world coordinates
  // Marching squares runs ONLY within these bounds (no ghost cells)
  bounds: AABB;

  // Physics collider handles for this chunk
  colliderHandles: Set<number>;

  // Dirty flag
  isDirty: boolean;

  // Loops generated by marching squares (for this chunk)
  loops: Point[][];

  // Original loops (before optimization) for debug visualization
  originalLoops: Point[][];
}

export class ChunkManager {
  private chunks: Map<string, Chunk> = new Map();
  private densityField: DensityField;
  private chunkSize: number; // metres
  private worldWidth: number;
  private worldHeight: number;
  private gridPitch: number;
  private chunksX: number;
  private chunksY: number;

  constructor(densityField: DensityField, chunkSize: number = 8.0) {
    this.densityField = densityField;
    this.chunkSize = chunkSize;
    this.worldWidth = densityField.config.width;
    this.worldHeight = densityField.config.height;
    this.gridPitch = densityField.config.gridPitch;

    // Calculate number of chunks in each dimension
    this.chunksX = Math.ceil(this.worldWidth / chunkSize);
    this.chunksY = Math.ceil(this.worldHeight / chunkSize);

    console.log(`[ChunkManager] Initializing ${this.chunksX}×${this.chunksY} = ${this.chunksX * this.chunksY} fully independent chunks (${chunkSize}m × ${chunkSize}m, no ghost cells)`);

    // Initialize all chunks
    this.initializeChunks();
  }

  /**
   * Initialize all chunks in the grid
   */
  private initializeChunks(): void {
    for (let gy = 0; gy < this.chunksY; gy++) {
      for (let gx = 0; gx < this.chunksX; gx++) {
        const chunk = this.createChunk(gx, gy);
        this.chunks.set(this.getChunkKey(gx, gy), chunk);
      }
    }
  }

  /**
   * Create a single chunk
   * Each chunk is fully independent with no ghost cells
   */
  private createChunk(gridX: number, gridY: number): Chunk {
    // Chunk bounds in world coordinates
    const minX = gridX * this.chunkSize;
    const minY = gridY * this.chunkSize;
    const maxX = Math.min(minX + this.chunkSize, this.worldWidth);
    const maxY = Math.min(minY + this.chunkSize, this.worldHeight);

    return {
      gridX,
      gridY,
      bounds: { minX, minY, maxX, maxY },
      colliderHandles: new Set(),
      isDirty: false,
      loops: [],
      originalLoops: [],
    };
  }

  /**
   * Get chunk key for map storage
   */
  private getChunkKey(gridX: number, gridY: number): string {
    return `${gridX},${gridY}`;
  }

  /**
   * Get chunk at world coordinates
   */
  getChunkAt(worldX: number, worldY: number): Chunk | undefined {
    const gx = Math.floor(worldX / this.chunkSize);
    const gy = Math.floor(worldY / this.chunkSize);
    return this.chunks.get(this.getChunkKey(gx, gy));
  }

  /**
   * Get chunk by grid coordinates
   */
  getChunkByGrid(gridX: number, gridY: number): Chunk | undefined {
    return this.chunks.get(this.getChunkKey(gridX, gridY));
  }

  /**
   * Get all chunks affected by an AABB (e.g., brush stroke)
   */
  getAffectedChunks(aabb: AABB): Chunk[] {
    const affected: Chunk[] = [];

    // Find chunk grid bounds that intersect the AABB
    const minChunkX = Math.max(0, Math.floor(aabb.minX / this.chunkSize));
    const minChunkY = Math.max(0, Math.floor(aabb.minY / this.chunkSize));
    const maxChunkX = Math.min(this.chunksX - 1, Math.floor(aabb.maxX / this.chunkSize));
    const maxChunkY = Math.min(this.chunksY - 1, Math.floor(aabb.maxY / this.chunkSize));

    for (let gy = minChunkY; gy <= maxChunkY; gy++) {
      for (let gx = minChunkX; gx <= maxChunkX; gx++) {
        const chunk = this.getChunkByGrid(gx, gy);
        if (chunk) {
          affected.push(chunk);
        }
      }
    }

    return affected;
  }

  /**
   * Mark chunks as dirty based on density field changes
   */
  markDirtyFromAABB(aabb: AABB): void {
    const affected = this.getAffectedChunks(aabb);
    for (const chunk of affected) {
      chunk.isDirty = true;
    }
    console.log(`[ChunkManager] Marked ${affected.length} chunks as dirty`);
  }

  /**
   * Get all dirty chunks
   */
  getDirtyChunks(): Chunk[] {
    const dirty: Chunk[] = [];
    for (const chunk of this.chunks.values()) {
      if (chunk.isDirty) {
        dirty.push(chunk);
      }
    }
    return dirty;
  }

  /**
   * Get all chunks
   */
  getAllChunks(): Chunk[] {
    return Array.from(this.chunks.values());
  }

  /**
   * Mark all chunks as dirty
   */
  markAllDirty(): void {
    for (const chunk of this.chunks.values()) {
      chunk.isDirty = true;
    }
  }

  /**
   * Clear all dirty flags
   */
  clearAllDirty(): void {
    for (const chunk of this.chunks.values()) {
      chunk.isDirty = false;
    }
  }

  /**
   * Clear a specific chunk
   */
  clearChunk(chunk: Chunk): void {
    chunk.loops = [];
    chunk.originalLoops = [];
    chunk.colliderHandles.clear();
    chunk.isDirty = false;
  }

  /**
   * Get chunk marching squares AABB
   * Returns the chunk bounds directly (no ghost cells)
   * Each chunk processes ONLY its own region
   */
  getChunkMarchingAABB(chunk: Chunk): AABB {
    return chunk.bounds;
  }

  /**
   * Get chunk grid dimensions (for visualization)
   */
  getChunkGridDimensions(): { chunksX: number; chunksY: number; chunkSize: number } {
    return {
      chunksX: this.chunksX,
      chunksY: this.chunksY,
      chunkSize: this.chunkSize,
    };
  }

  /**
   * Debug: Get chunk info string
   */
  getChunkInfo(chunk: Chunk): string {
    return `Chunk(${chunk.gridX},${chunk.gridY}) [${chunk.bounds.minX.toFixed(1)},${chunk.bounds.minY.toFixed(1)}]→[${chunk.bounds.maxX.toFixed(1)},${chunk.bounds.maxY.toFixed(1)}] loops=${chunk.loops.length} colliders=${chunk.colliderHandles.size} dirty=${chunk.isDirty}`;
  }
}
